name: GitHub Actions Demo
on: [push]
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.'
      - name: Run Python script
        run: python job.py